import { Provider } from 'react-redux'
import { Footer, Header } from './components'
import './globals.css'
import { Inter } from 'next/font/google'

import Providers from './components/Providers'

const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Online Shoe Store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
  
      <body className={inter.className}>
        <Providers>
        <Header />
        {children}
        <Footer />
        </Providers>
        </body>
       
    </html>
    
  )
}
